joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
# gazebo_ros_control:
#   pid_gains:
#     gripper_joint:
#       p: 1.0
#       i: 0.0
#       d: 0.0
#       i_clamp: 0.2
#       antiwindup: false
#       publish_state: true
#     l_finger_2_joint:
#       p: 1.0
#       i: 0.0
#       d: 0.0
#       i_clamp: 0.2
#       antiwindup: false
#       publish_state: true
#     l_finger_passive_joint:
#       p: 1.0
#       i: 0.0
#       d: 0.0
#       i_clamp: 0.2
#       antiwindup: false
#       publish_state: true
#     r_finger_1_joint:
#       p: 1.0
#       i: 0.0
#       d: 0.0
#       i_clamp: 0.2
#       antiwindup: false
#       publish_state: true
#     r_finger_2_joint:
#       p: 1.0
#       i: 0.0
#       d: 0.0
#       i_clamp: 0.2
#       antiwindup: false
#       publish_state: true
#     r_finger_passive_joint:
#       p: 1.0
#       i: 0.0
#       d: 0.0
#       i_clamp: 0.2
#       antiwindup: false
#       publish_state: true
#     shoulder_pan_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#       antiwindup: false
#       publish_state: true
#     shoulder_lift_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#       antiwindup: false
#       publish_state: true
#     elbow_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#       antiwindup: false
#       publish_state: true

#     wrist_1_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#       antiwindup: false
#       publish_state: true
#     wrist_2_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#       antiwindup: false
#       publish_state: true
#     wrist_3_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#       antiwindup: false
#       publish_state: true
